version: "3.8"

services:
  db:
    image: postgres:16
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    command: postgres -c max_connections=30 -c shared_buffers=128MB -c fsync=off -c synchronous_commit=off -c checkpoint_timeout=1d -c full_page_writes=false
    network_mode: host
    environment:
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha
      POSTGRES_DB: rinha
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "300MB"
